### ISSUE TITLE
Cant compile with Swedish characters

### ISSUE THREAD

**Issue by pandersson06** [axhav/lekstuga#5]
When cloning repo to linux, can't compile. åäö is encoded badly for linux. Plz use utf-8.

**Comment by joacand** [comment]
Alternatively, compile the following way:
javac -encoding ISO-8859-1 -cp ...

I suggest adding this to README if changing encoding on file is not desired.
(Problem is java compilers that default to UTF-8 encoding gets error when compiling. So users need to proving -encoding parameter when compiling as long as the file is encoded with ISO-8859-1.)

**Comment by axhav** [comment]
updated readme
